    code:`#!/usr/bin/env node
// src/cli.ts — UPDATED: --ignore flag with safe defaults
// Installs as the 'delta' binary via package.json "bin" field.
// Usage:
//   delta run   <file.delta> [--preview] [--verbose]
//   delta check <file.delta>
//   delta trace <file.delta>
//   delta init  [--lang ts|py|go|rust]

import { Command }  from "commander";
import chalk        from "chalk";
import ora          from "ora";
import * as fs      from "fs";
import * as path    from "path";
import { tokenise } from "./lexer";
import { parse }    from "./parser";
import { resolve }  from "./resolver";
import { emit }     from "./emitter";
import { DEFAULT_IGNORE } from "./guards";

const pkg = require("../package.json");
const program = new Command();

program.name("delta")
  .description("Delta — Universal Code Transformation Language")
  .version(pkg.version);

program
  .command("run <file>")
  .description("Run a .delta transformation file")
  .option("-p, --preview",           "Show diff without writing to disk")
  .option("-v, --verbose",           "Verbose output")
  .option("--cwd <dir>",             "Working directory", process.cwd())
  .option("--ignore <patterns...>",  "Extra glob patterns to ignore", [])
  .action(async (file: string, opts) => {
    const spinner = ora(\`Running \${chalk.yellow(file)}\`).start();
    try {
      const src = fs.readFileSync(path.resolve(opts.cwd, file), "utf8");
      const { order, registry, diagnostics, hasErrors } = resolve(parse(tokenise(src)), opts.cwd);
      for (const d of diagnostics) {
        if (d.severity==="error")   spinner.fail(chalk.red(\`Error: \${d.message}\`));
        if (d.severity==="warning") console.warn(chalk.yellow(\`Warning: \${d.message}\`));
      }
      if (hasErrors) process.exit(1);

      const ignore = [...DEFAULT_IGNORE, ...(opts.ignore ?? [])];
      const results = await emit(order, registry, {
        cwd: opts.cwd, preview: opts.preview ?? false,
        verbose: opts.verbose ?? false, ignore,
      });
      const applied   = results.filter(r => r.applied).length;
      const previewed = results.filter(r => !r.applied).length;
      if (opts.preview)
        spinner.succeed(chalk.cyan(\`Preview: \${previewed} file(s) would be modified\`));
      else
        spinner.succeed(chalk.green(\`Done: \${applied} file(s) modified\`));
    } catch (err: any) {
      spinner.fail(chalk.red(err.message));
      if (opts.verbose) console.error(err.stack);
      process.exit(1);
    }
  });

program
  .command("check <file>")
  .description("Validate a .delta file without running it")
  .option("--cwd <dir>","Working directory", process.cwd())
  .action(async (file: string, opts) => {
    try {
      const { diagnostics } = resolve(parse(tokenise(
        fs.readFileSync(path.resolve(opts.cwd, file),"utf8")
      )), opts.cwd);
      let hasError = false;
      for (const d of diagnostics) {
        const icon = d.severity==="error" ? chalk.red("✗") : chalk.yellow("⚠");
        console.log(\`\${icon} [\${d.span.start.line}:\${d.span.start.col}] \${d.message}\`);
        if (d.severity==="error") hasError = true;
      }
      if (!hasError) console.log(chalk.green("✓ No errors found"));
      process.exit(hasError ? 1 : 0);
    } catch (e: any) { console.error(chalk.red(e.message)); process.exit(1); }
  });

program
  .command("init")
  .description("Scaffold a starter .delta file")
  .option("--lang <lang>","Primary language (ts|py|go|rust)","ts")
  .option("--cwd <dir>",  "Output directory", process.cwd())
  .action((opts) => {
    const out = path.join(opts.cwd,"transform.delta");
    fs.writeFileSync(out,
\`// generated by: delta init --lang \${opts.lang}

guard "baseline" {
  scope:   "src/**"
  assert:  all exported fns have return types
  on_fail: warn
}

// Add your patch, fix, intent, or migrate blocks here
// Preview: delta run transform.delta --preview
// Apply:   delta run transform.delta
\`,"utf8");
    console.log(chalk.green(\`✓ Created \${out}\`));
  });

program.parse(process.argv);`
  },
{      ts: "TypeScript", py: "Python", go: "Go", rust: "Rust"
    };
    const lang = langMap[opts.lang] ?? "TypeScript";
    const template = \`// generated by: delta init --lang \${opts.lang}

guard "baseline" {
  scope:   "src/**"
  assert:  all exported fns have return types
  on_fail: warn
}

// Add your patch, fix, intent, or migrate blocks here
// Run with: delta run transform.delta --preview
\`;
    const out = path.join(opts.cwd, "transform.delta");
    fs.writeFileSync(out, template, "utf8");
    console.log(chalk.green(\`✓ Created \${out}\`));
  });

program.parse(process.argv);
