#!/usr/bin/env node
// src/cli.ts
// ─── Delta CLI ────────────────────────────────────────────────────────────
// UPDATED: --ignore flag added with safe defaults.
// Commands: delta run, delta check, delta init

import { Command }  from "commander";
import chalk        from "chalk";
import ora          from "ora";
import * as fs      from "fs";
import * as path    from "path";
import { tokenise } from "./lexer";
import { parse }    from "./parser";
import { resolve }  from "./resolver";
import { emit }     from "./emitter";
import { DEFAULT_IGNORE } from "./guards";

const pkg     = require("../package.json");
const program = new Command();

program
  .name("delta")
  .description("Delta — Universal Code Transformation Language")
  .version(pkg.version);

// ── delta run ─────────────────────────────────────────────────────────────
program
  .command("run <file>")
  .description("Run a .delta transformation file")
  .option("-p, --preview",           "Show diff without writing to disk")
  .option("-v, --verbose",           "Verbose output")
  .option("--cwd <dir>",             "Working directory", process.cwd())
  .option(
    "--ignore <patterns...>",
    "Extra glob patterns to ignore (added to safe defaults)",
    []
  )
  .action(async (file: string, opts) => {
    const spinner = ora(`Running ${chalk.yellow(file)}`).start();
    try {
      const src = fs.readFileSync(path.resolve(opts.cwd, file), "utf8");
      const tokens = tokenise(src);
      const ast    = parse(tokens);
      const { order, registry, diagnostics, hasErrors } = resolve(ast, opts.cwd);

      for (const d of diagnostics) {
        if (d.severity === "error")
          spinner.fail(chalk.red(`Error: ${d.message}`));
        if (d.severity === "warning")
          console.warn(chalk.yellow(`Warning: ${d.message}`));
      }
      if (hasErrors) process.exit(1);

      // Merge user-supplied patterns with the safe defaults from guards.ts
      const ignore = [...DEFAULT_IGNORE, ...(opts.ignore ?? [])];

      spinner.text = "Applying transformations…";
      const results = await emit(order, registry, {
        cwd:     opts.cwd,
        preview: opts.preview ?? false,
        verbose: opts.verbose ?? false,
        ignore,
      });

      const applied   = results.filter(r => r.applied).length;
      const previewed = results.filter(r => !r.applied).length;

      if (opts.preview) {
        spinner.succeed(
          chalk.cyan(`Preview: ${previewed} file(s) would be modified`)
        );
      } else {
        spinner.succeed(
          chalk.green(`Done: ${applied} file(s) modified`)
        );
      }
    } catch (err: any) {
      spinner.fail(chalk.red(err.message));
      if (opts.verbose) console.error(err.stack);
      process.exit(1);
    }
  });

// ── delta check ───────────────────────────────────────────────────────────
program
  .command("check <file>")
  .description("Parse and validate a .delta file without running it")
  .option("--cwd <dir>", "Working directory", process.cwd())
  .action(async (file: string, opts) => {
    try {
      const src = fs.readFileSync(path.resolve(opts.cwd, file), "utf8");
      const ast = parse(tokenise(src));
      const { diagnostics } = resolve(ast, opts.cwd);
      let hasError = false;
      for (const d of diagnostics) {
        const icon = d.severity === "error"
          ? chalk.red("✗")
          : chalk.yellow("⚠");
        console.log(
          `${icon} [${d.span.start.line}:${d.span.start.col}] ${d.message}`
        );
        if (d.severity === "error") hasError = true;
      }
      if (!hasError) console.log(chalk.green("✓ No errors found"));
      process.exit(hasError ? 1 : 0);
    } catch (e: any) {
      console.error(chalk.red(e.message));
      process.exit(1);
    }
  });

// ── delta init ────────────────────────────────────────────────────────────
program
  .command("init")
  .description("Scaffold a starter .delta file for your project")
  .option("--lang <lang>", "Primary language (ts|py|go|rust)", "ts")
  .option("--cwd <dir>",   "Output directory", process.cwd())
  .action((opts) => {
    const template = `// generated by: delta init --lang ${opts.lang}

guard "baseline" {
  scope:   "src/**"
  assert:  all exported fns have return types
  on_fail: warn
}

// Add your patch, fix, intent, or migrate blocks here
// Preview changes first: delta run transform.delta --preview
// Apply changes:         delta run transform.delta
`;
    const out = path.join(opts.cwd, "transform.delta");
    fs.writeFileSync(out, template, "utf8");
    console.log(chalk.green(`✓ Created ${out}`));
  });

program.parse(process.argv);
